# Generated by Django 5.2.2 on 2026-04-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pozosscz', '0033_estadocamion_direccion_estadocamion_velocidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelChoferes',
            fields=[
            ],
            options={
                'verbose_name': 'Panel de Choferes',
                'verbose_name_plural': 'Panel de Choferes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pozosscz.camion',),
        ),
    ]
