# Generated by Django 5.2.2 on 2026-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_camion_estadocamion_dispositivofcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispositivofcm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadocamion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='estadocamion',
            index=models.Index(fields=['camion', 'registrado_at'], name='pozosscz_es_camion__77da9f_idx'),
        ),
    ]
