# Generated by Django 5.2.2 on 2026-04-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_rename_app_moviles_to_flota'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocamion',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Comentario'),
        ),
    ]
