# Generated by Django 5.2.2 on 2026-04-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_rename_estadocamion_to_registrocamion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocamion',
            options={'ordering': ['-registrado_at'], 'verbose_name': 'Registro de Camión', 'verbose_name_plural': 'Registros de Camión'},
        ),
    ]
