# Generated by Django 5.2.2 on 2026-04-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_cliente_orden'),
        ('flota', '0007_cliente_camion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SRV_EJE', 'Servicio ejecutado'), ('SRV_CAN', 'Servicio cancelado'), ('TKQ_VAC', 'Tanque vaciado en planta'), ('TKQ_UPD', 'Nivel tanque actualizado'), ('DSL_CAR', 'Diesel cargado')], max_length=7, verbose_name='Tipo de evento')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('motivo_cancelacion', models.TextField(blank=True, default='', verbose_name='Motivo de cancelación')),
                ('nivel_tanque', models.FloatField(blank=True, null=True, verbose_name='Nivel tanque (0.0–1.0)')),
                ('diesel', models.IntegerField(blank=True, null=True, verbose_name='Diesel cargado (Bs)')),
                ('registrado_at', models.DateTimeField(auto_now_add=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='flota.camion', verbose_name='Camión')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='clientes.cliente', verbose_name='Cliente (servicio)')),
            ],
            options={
                'verbose_name': 'Evento de Camión',
                'verbose_name_plural': 'Eventos de Camión',
                'db_table': 'pozosscz_eventocamion',
                'ordering': ['-registrado_at'],
                'indexes': [models.Index(fields=['camion', 'registrado_at'], name='pozosscz_ev_camion__9dcc72_idx'), models.Index(fields=['tipo', 'registrado_at'], name='pozosscz_ev_tipo_0709c1_idx')],
            },
        ),
    ]
