# Generated by Django 5.2.2 on 2026-04-15 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_eventocamion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocamion',
            name='diesel',
        ),
        migrations.RemoveField(
            model_name='registrocamion',
            name='nivel_tanque',
        ),
    ]
