# Generated by Django 5.2.2 on 2026-04-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_remove_registrocamion_diesel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocamion',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Comentario'),
        ),
    ]
