# Generated by Django 5.2.2 on 2026-04-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0010_eventocamion_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocamion',
            name='diesel',
        ),
        migrations.AddField(
            model_name='eventocamion',
            name='monto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto'),
        ),
    ]
