# Generated by Django 5.2.2 on 2026-04-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0011_rename_diesel_to_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocamion',
            name='motivo_cancelacion',
        ),
    ]
