# Generated by Django 5.2.2 on 2026-04-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0012_remove_eventocamion_motivo_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocamion',
            name='nivel_tanque',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nivel tanque (%)'),
        ),
    ]
