# Generated by Django 5.2.2 on 2026-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0013_alter_eventocamion_nivel_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocamion',
            name='qr',
            field=models.BooleanField(default=True, verbose_name='QR'),
        ),
        migrations.AlterField(
            model_name='eventocamion',
            name='nivel_tanque',
            field=models.FloatField(blank=True, null=True, verbose_name='Nivel tanque'),
        ),
        migrations.AlterField(
            model_name='eventocamion',
            name='tipo',
            field=models.CharField(choices=[('SRV_EJE', 'Servicio ejecutado'), ('SRV_CAN', 'Servicio cancelado'), ('TKQ_VAC', 'Tanque vacío'), ('TKQ_UPD', 'Nivel tanque actualizado'), ('TKQ_LLE', 'Tanque lleno'), ('DSL_CAR', 'Diesel cargado'), ('TRK_ACT', 'Activado'), ('TRK_DES', 'Desactivado')], max_length=7, verbose_name='Tipo de evento'),
        ),
    ]
