# Generated by Django 5.2.2 on 2026-04-15 16:37

from django.db import migrations, models


def backfill_factura(apps, schema_editor):
    EventoCamion = apps.get_model('flota', 'EventoCamion')
    qs = EventoCamion.objects.filter(factura__isnull=True, monto__isnull=False)
    for ev in qs:
        ev.factura = round(ev.monto * 0.84)
    EventoCamion.objects.bulk_update(qs, ['factura'])


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0014_eventocamion_qr_alter_eventocamion_nivel_tanque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocamion',
            name='factura',
            field=models.IntegerField(blank=True, help_text='Se autocompleta con monto − 16% si se deja vacío', null=True, verbose_name='Factura'),
        ),
        migrations.RunPython(backfill_factura, migrations.RunPython.noop),
    ]
