# Generated by Django 5.2.2 on 2026-04-15 16:41

from django.db import migrations, models


def clear_factura(apps, schema_editor):
    EventoCamion = apps.get_model('flota', 'EventoCamion')
    EventoCamion.objects.filter(factura__isnull=False).update(factura=None)


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0015_eventocamion_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocamion',
            name='factura',
            field=models.IntegerField(blank=True, help_text='Monto facturado (monto − 16%); vacío hasta que se confirme manualmente', null=True, verbose_name='Factura'),
        ),
        migrations.RunPython(clear_factura, migrations.RunPython.noop),
    ]
