# docker-compose.yml
services:
  postgres:
    image: postgres:15-alpine  
    container_name: postgres_db
    ports:
      - "5435:5432"
    env_file:
      - .env  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - pozos_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6381:6379"
    networks:
      - pozos_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: ./entrypoint.sh
    volumes:
      - ./staticfiles:/app/staticfiles  
      - ./media:/app/media    
    ports:
      - "8003:8000"  
    env_file:
      - .env  
    depends_on:
      - postgres
      - redis
    networks:
      - pozos_network

volumes:
  postgres_data:
  static:
  media:

networks:
  pozos_network:
