# docker-compose.yml
services:
  redis:
    image: redis:alpine
    container_name: pozosscz_redis
    networks:
      - pozos_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pozosscz_app
    command: ./entrypoint.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8004:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - pozos_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  static:
  media:

networks:
  pozos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.64.0/24
