# Generated by Django 5.2.1 on 2025-06-02 21:10

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='svg',
            field=models.FileField(help_text='Upload an SVG file', upload_to='banner/', validators=[main.models.validate_svg]),
        ),
    ]
