# Generated by Django 5.2.1 on 2025-06-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_active_alter_banner_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='active',
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Solo un banner puede estar activo'),
        ),
    ]
