# Generated by Django 5.2.1 on 2025-06-02 22:57

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_banner_active_banner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_svg', models.FileField(help_text='Upload an SVG file', upload_to='alcance/', validators=[main.models.validate_svg])),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
