# Generated by Django 5.2.1 on 2025-06-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alcance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alcance',
            options={'verbose_name': 'Alcance', 'verbose_name_plural': 'Alcance'},
        ),
        migrations.AddField(
            model_name='alcance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
