# Generated by Django 5.2.1 on 2025-06-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_alcance_options_alcance_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alcance',
            options={'ordering': ['order'], 'verbose_name': 'Alcance', 'verbose_name_plural': 'Alcance'},
        ),
        migrations.AddField(
            model_name='alcance',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
