# Generated by Django 5.2.1 on 2025-06-03 00:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tipocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocliente',
            name='img_svg',
            field=models.FileField(default=1, help_text='Upload an SVG file', upload_to='tipo_cliente/', validators=[main.models.validate_svg]),
            preserve_default=False,
        ),
    ]
