# Generated by Django 5.2.2 on 2025-06-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_metatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatag',
            name='extra_props',
            field=models.JSONField(blank=True, default={'viewport': 'width=device-width, initial-scale=1.0'}),
        ),
    ]
