# Generated by Django 5.2.2 on 2025-06-10 15:45

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_metatag_extra_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='extra_props',
            field=models.JSONField(blank=True, default=main.models.default_extra_props),
        ),
    ]
