# Generated by Django 5.2.1 on 2025-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasfactor',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
