# Generated by Django 5.2.1 on 2025-06-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0002_areasfactor_is_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='areasfactor',
            options={'ordering': ['my_order'], 'verbose_name': 'Área y Factor', 'verbose_name_plural': 'Áreas y Factores'},
        ),
        migrations.AlterField(
            model_name='areasfactor',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
    ]
