# Generated by Django 5.2.1 on 2025-06-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0004_basecamion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecamion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='basecamion',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
