# Generated by Django 5.2.1 on 2025-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0005_remove_basecamion_updated_at_basecamion_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecamion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basecamion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
