# Generated by Django 5.2.1 on 2025-06-06 15:41

import pozosscz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0006_basecamion_deleted_basecamion_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='p_base',
        ),
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='p_factor',
        ),
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='p_km',
        ),
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='p_tiempo',
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='consumo_diesel_hora',
            field=models.FloatField(default=12, help_text='Consumo de diesel en L/Hr', verbose_name='Consumo Diesel (L/Hr)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='consumo_diesel_km',
            field=models.JSONField(default=pozosscz.models.PreciosPozosSCZ.default_consumo_km, help_text='Consumo de diesel en Km/L (camión vacío y lleno)', verbose_name='Consumo Diesel (Km/L)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='factor_tiempo',
            field=models.FloatField(default=1.25, help_text='Factor tiempo en min', verbose_name='Factor tiempo (min)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='personal_camion',
            field=models.FloatField(default=40, help_text='Costo de personal en %', verbose_name='Personal %'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='precio_base',
            field=models.FloatField(default=350, help_text='Precio base en Bs', verbose_name='Precio base (Bs)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='precio_diesel',
            field=models.FloatField(default=3.76, help_text='Precio del diesel en Bs/L', verbose_name='Precio Diesel (Bs)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='precio_transporte',
            field=models.FloatField(default=7, help_text='Costo de transporte en Bs/km', verbose_name='Costo transporte (Bs/km)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='tiempo_trabajo',
            field=models.FloatField(default=30, help_text='Tiempo de trabajo en min', verbose_name='Tiempo de trabajo (min)'),
        ),
    ]
