# Generated by Django 5.2.1 on 2025-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0007_remove_preciospozosscz_p_base_and_more'),
    ]

    operations = [
    ]
