# Generated by Django 5.2.1 on 2025-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0008_fix_consumo_diesel_hora_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='consumo_diesel_hora',
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='consumo_diesel_hr',
            field=models.FloatField(default=12, help_text='Consumo de diesel en L/Hr', verbose_name='Consumo Diesel (L/Hr)'),
        ),
    ]
