# Generated by Django 5.2.1 on 2025-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0009_remove_preciospozosscz_consumo_diesel_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciospozosscz',
            name='costo_saguapac_km',
            field=models.IntegerField(default=30, help_text='Costo de Saguapac Tratamiento planta en Bs.', verbose_name='Costo Saguapac Panta'),
        ),
    ]
