# Generated by Django 5.2.1 on 2025-06-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0010_preciospozosscz_costo_saguapac_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciospozosscz',
            name='costo_mantenimiento',
            field=models.FloatField(default=5, help_text='Costo de mantenimiento en Bs.', verbose_name='Costo Mantenimiento %'),
        ),
    ]
