# Generated by Django 5.2.1 on 2025-06-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0011_preciospozosscz_costo_mantenimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciospozosscz',
            old_name='costo_saguapac_km',
            new_name='costo_saguapac_planta',
        ),
    ]
