# Generated by Django 5.2.1 on 2025-06-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0012_rename_costo_saguapac_km_preciospozosscz_costo_saguapac_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciospozosscz',
            name='costo_mantenimiento',
            field=models.IntegerField(default=20, help_text='Costo de mantenimiento en Bs.', verbose_name='Costo Mantenimiento %'),
        ),
    ]
