# Generated by Django 5.2.1 on 2025-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0014_alter_preciospozosscz_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciospozosscz',
            name='personal_camion',
            field=models.IntegerField(default=20, help_text='Costo de personal en %', verbose_name='Personal %'),
        ),
    ]
