# Generated by Django 5.2.1 on 2025-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0015_alter_preciospozosscz_personal_camion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='precio_base',
        ),
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='precio_transporte',
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='utilidad_base',
            field=models.IntegerField(default=200, help_text='Utilidad base en Bs.', verbose_name='Utilidad base (Bs)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='utilidad_km',
            field=models.FloatField(default=6, help_text='Utilidad en %', verbose_name='Utilidad Km'),
        ),
    ]
