# Generated by Django 5.2.1 on 2025-06-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0016_remove_preciospozosscz_precio_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciospozosscz',
            name='costo_adicional_km_retorno',
            field=models.IntegerField(default=1, help_text='Costo adicional en Bs/Km.', verbose_name='Costo adicional Km > 20 km'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='utilidad_base',
            field=models.IntegerField(default=140, help_text='Utilidad base en Bs.', verbose_name='Utilidad base (Bs)'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='utilidad_km',
            field=models.FloatField(default=5, help_text='Utilidad en %', verbose_name='Utilidad Km 20% de ida y 80% retorno'),
        ),
    ]
