# Generated by Django 5.2.1 on 2025-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0017_preciospozosscz_costo_adicional_km_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciospozosscz',
            name='costo_adicional_km_retorno',
            field=models.FloatField(default=1.2, help_text='Costo adicional en Bs/Km.', verbose_name='Costo adicional Km > 20 km'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='utilidad_base',
            field=models.IntegerField(default=160, help_text='Utilidad base en Bs.', verbose_name='Utilidad base (Bs)'),
        ),
    ]
