# Generated by Django 5.2.1 on 2025-06-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0018_alter_preciospozosscz_costo_adicional_km_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciospozosscz',
            name='costo_adicional_km_retorno',
            field=models.FloatField(default=1, help_text='Costo adicional en Bs/Km.', verbose_name='Costo adicional Km > 20 km'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='utilidad_km',
            field=models.FloatField(default=5, help_text='Utilidad en %', verbose_name='Utilidad Km 50% de ida y 50% retorno'),
        ),
    ]
