# Generated by Django 5.2.1 on 2025-06-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0020_alter_datosgenerales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='correo',
            field=models.EmailField(default='info@pozosscz.com', max_length=100, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='mensaje_cotizar',
            field=models.TextField(default='Precio del servicio de limpieza del pozo y cámara séptica para vivienda.', verbose_name='Mensaje para Cotizar'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='mensaje_whatsapp',
            field=models.TextField(default='¡Hola!, Requiero el servicio de limpieza en la siguiente ubicación: ', verbose_name='Mensaje para Whatsapp'),
        ),
    ]
