# Generated by Django 5.2.2 on 2025-06-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0021_datosgenerales_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciospozosscz',
            name='distancia_maxima_cotizar',
            field=models.IntegerField(default=50, help_text='Distancia máxima para cotizar en Km.', verbose_name='Distancia máxima para cotizar (Km)'),
        ),
    ]
