# Generated by Django 5.2.2 on 2025-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0022_preciospozosscz_distancia_maxima_cotizar'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciospozosscz',
            name='factor_global',
            field=models.FloatField(default=1, help_text='Factor global por defecto 1.', verbose_name='Factor precio final'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='costo_adicional_km_retorno',
            field=models.FloatField(default=1, help_text='Costo adicional de retorno (>20km) en Bs/Km.', verbose_name='Costo adicional Km > 20 km'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='distancia_maxima_cotizar',
            field=models.IntegerField(default=60, help_text='Distancia máxima para cotizar en Km. linea recta desde centro de SCZ.', verbose_name='Distancia máxima para cotizar (Km)'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='factor_tiempo',
            field=models.FloatField(default=1.25, help_text='Factor tiempo en min', verbose_name='Factor tiempo Camion/auto (min)'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='utilidad_km',
            field=models.FloatField(default=5, help_text='Utilidad en Bs/Km', verbose_name='Utilidad Km 50% de ida y 50% retorno'),
        ),
    ]
