# Generated by Django 5.2.2 on 2026-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0023_preciospozosscz_factor_global_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecamion',
            options={'verbose_name': 'Base de Camión', 'verbose_name_plural': 'Bases de Camiones'},
        ),
        migrations.AddIndex(
            model_name='areasfactor',
            index=models.Index(fields=['is_main'], name='pozosscz_ar_is_main_fc05d4_idx'),
        ),
        migrations.AddIndex(
            model_name='basecamion',
            index=models.Index(fields=['available', 'deleted'], name='pozosscz_ba_availab_e9083a_idx'),
        ),
    ]
