# Generated by Django 5.2.2 on 2026-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0024_alter_basecamion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='consumo_diesel_km',
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='factor_cargado',
            field=models.FloatField(default=1.05, help_text='Factor adicional de tiempo cuando el camión va cargado en retorno (ej: 1.05 = 5% más lento)', verbose_name='Factor retorno cargado'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='tiempo_minimo_cobro',
            field=models.FloatField(default=90, help_text='Tiempo mínimo facturable en minutos, aunque el servicio sea más corto', verbose_name='Tiempo mínimo de cobro (min)'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='factor_tiempo',
            field=models.FloatField(default=1.25, help_text='El camión tarda este factor más que un auto (ej: 1.25 = 25% más lento)', verbose_name='Factor velocidad camión vs auto'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='personal_camion',
            field=models.IntegerField(default=15, help_text='% del precio final para el operador', verbose_name='Personal %'),
        ),
    ]
