# Generated by Django 5.2.2 on 2026-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0025_remove_preciospozosscz_consumo_diesel_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciospozosscz',
            name='consumo_diesel_hr',
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='consumo_trabajo_hr',
            field=models.FloatField(default=16, help_text='Consumo de diesel durante el trabajo en sitio (bomba activa) en L/Hr', verbose_name='Consumo trabajo (L/Hr)'),
        ),
        migrations.AddField(
            model_name='preciospozosscz',
            name='consumo_viaje_hr',
            field=models.FloatField(default=10, help_text='Consumo de diesel durante el viaje (sin bomba activa) en L/Hr', verbose_name='Consumo viaje (L/Hr)'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='costo_adicional_km_retorno',
            field=models.FloatField(default=1, help_text='Utilidad en Bs/Km por el recorrido de retorno a Saguapac', verbose_name='Utilidad retorno a Saguapac (Bs/Km)'),
        ),
        migrations.AlterField(
            model_name='preciospozosscz',
            name='utilidad_km',
            field=models.FloatField(default=5, help_text='Utilidad en Bs/Km por el recorrido de ida a la ubicación del cliente', verbose_name='Utilidad recorrido de ida (Bs/Km)'),
        ),
    ]
