# Generated by Django 5.2.2 on 2026-04-10 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0028_camion_estadocamion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='estadocamion',
            new_name='pozosscz_es_camion__77da9f_idx',
            old_name='pozosscz_es_camion__idx',
        ),
    ]
