# Generated by Django 5.2.2 on 2026-04-11 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0029_rename_pozosscz_es_camion__idx_pozosscz_es_camion__77da9f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario chofer'),
        ),
        migrations.CreateModel(
            name='DispositivoFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True, verbose_name='Token FCM')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('registrado_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo FCM',
                'verbose_name_plural': 'Dispositivos FCM',
            },
        ),
    ]
