# Generated by Django 5.2.2 on 2026-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0030_camion_usuario_dispositivofcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='En servicio'),
        ),
        migrations.AddField(
            model_name='camion',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Última latitud'),
        ),
        migrations.AddField(
            model_name='camion',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Último longitud'),
        ),
        migrations.AddField(
            model_name='camion',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización'),
        ),
    ]
