# Generated by Django 5.2.2 on 2026-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0031_camion_activo_camion_lat_camion_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='intervalo_tracking',
            field=models.PositiveIntegerField(default=30, help_text='Cada cuántos segundos el teléfono envía su ubicación (mínimo 10)', verbose_name='Intervalo de tracking (seg)'),
        ),
        migrations.AddField(
            model_name='camion',
            name='tracking_activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el chofer no puede enviar ubicación', verbose_name='Tracking activo'),
        ),
    ]
