# Generated by Django 5.2.2 on 2026-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0032_camion_intervalo_tracking_camion_tracking_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocamion',
            name='direccion',
            field=models.FloatField(default=0, help_text='0=Norte, 90=Este, 180=Sur, 270=Oeste', verbose_name='Dirección (°)'),
        ),
        migrations.AddField(
            model_name='estadocamion',
            name='velocidad',
            field=models.FloatField(default=0, verbose_name='Velocidad (km/h)'),
        ),
    ]
