# Generated by Django 5.2.2 on 2026-06-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0034_remove_camion_estadocamion_dispositivofcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='hero_variant',
            field=models.CharField(choices=[('A', 'A — Split + foto'), ('B', 'B — Pasos + tarjeta de cotización'), ('C', 'C — Centrado + foto ancha'), ('D', 'D — Banner animado (versión anterior)')], default='A', help_text='Versión del hero de la página de inicio que ve el público.', max_length=1, verbose_name='Variante del inicio (hero)'),
        ),
    ]
