# Generated by Django 5.2.2 on 2026-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0035_datosgenerales_hero_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='hero_variant',
            field=models.CharField(choices=[('A', 'A — Rediseño (card de cotización)'), ('D', 'D — Banner animado (versión anterior)')], default='A', help_text='Versión del hero de la página de inicio que ve el público.', max_length=1, verbose_name='Variante del inicio (hero)'),
        ),
    ]
