# Generated by Django 5.2.2 on 2026-06-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0036_alter_datosgenerales_hero_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='celular',
            field=models.CharField(default='+59176644033', max_length=12, verbose_name='Teléfono Celular'),
        ),
    ]
