# Generated by Django 5.2.2 on 2026-06-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pozosscz', '0037_alter_datosgenerales_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='hero_imagen',
            field=models.ImageField(blank=True, help_text='Imagen del servicio que se muestra arriba del título en el inicio. Si se deja vacío, se usa la imagen por defecto.', null=True, upload_to='home/', verbose_name='Imagen del hero (inicio)'),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='hero_imagen_alt',
            field=models.CharField(default='Camión de limpieza de pozos sépticos en Santa Cruz', help_text='Descripción de la imagen para accesibilidad y SEO.', max_length=255, verbose_name='Texto alternativo de la imagen del hero'),
        ),
    ]
