# Generated by Django 5.1.1 on 2024-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateField(verbose_name='actualizado'),
        ),
    ]
