# Generated by Django 5.2.1 on 2025-06-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='actualizado'),
        ),
    ]
