# Generated by Django 5.2.1 on 2025-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='creado'),
        ),
    ]
