# Generated by Django 5.2.1 on 2025-06-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='creado'),
        ),
    ]
