# Generated by Django 5.2.2 on 2025-06-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cliente_updated_at_alter_cliente_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=120, verbose_name='direccion - comentario'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
    ]
