# Generated by Django 5.2.2 on 2025-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_address_alter_cliente_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel1',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='telefono 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel2',
            field=models.CharField(blank=True, max_length=13, verbose_name='telefono 2'),
        ),
    ]
