# Generated by Django 5.2.2 on 2025-06-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel2',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefono 2'),
        ),
    ]
