# Generated by Django 5.2.2 on 2025-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_tel1_alter_cliente_tel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.TextField(blank=True, max_length=255, verbose_name='direccion - comentario'),
        ),
    ]
