# Generated by Django 5.2.2 on 2026-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['status'], name='clientes_cl_status_b31356_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['created_at'], name='clientes_cl_created_cc2563_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['service'], name='clientes_cl_service_fa514f_idx'),
        ),
    ]
