# Generated by Django 5.2.2 on 2026-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precio_cotizado',
            field=models.IntegerField(default=0, help_text='Precio calculado por el sistema al momento de cotizar', verbose_name='precio cotizado'),
        ),
        # Copiar cost → precio_cotizado en registros existentes
        migrations.RunSQL(
            sql='UPDATE clientes_cliente SET precio_cotizado = cost WHERE precio_cotizado = 0',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='precio final'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('COT', 'Cotizado'), ('PRG', 'Programado'), ('EJE', 'Ejecutado'), ('NEG', 'L.negra')], default='COT', max_length=3, verbose_name='estado'),
        ),
    ]
