# Generated by Django 5.2.2 on 2026-04-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_precio_cotizado_y_estado_programado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='precio_cotizado',
            field=models.IntegerField(default=0, help_text='Precio calculado por el sistema al momento de cotizar', verbose_name='Precio sistema'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('COT', 'Cotizado'), ('PRG', 'Programado'), ('EJE', 'Ejecutado'), ('CAN', 'Cancelado'), ('NEG', 'L.negra')], default='COT', max_length=3, verbose_name='estado'),
        ),
    ]
