# Generated by Django 5.2.2 on 2026-04-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_add_cancelado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('COT', 'Cotizado'), ('PRG', 'Programado'), ('EJE', 'Ejecutado'), ('CAN', 'Cancelado'), ('PRB', 'Problema'), ('NEG', 'L.negra')], default='COT', max_length=3, verbose_name='estado'),
        ),
    ]
