# Generated by Django 5.2.2 on 2026-04-13 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_rename_jornada_cliente_activo'),
        ('flota', '0007_cliente_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='flota.camion', verbose_name='Camión asignado'),
        ),
    ]
