# Generated by Django 5.2.2 on 2026-04-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_cliente_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='orden',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='orden jornada'),
        ),
    ]
